In [1]:
import numpy as np

In [2]:
escalar = 4
vector = np.array([1,2,4,5,7])
matriz = np.array([[1,2,3,4,5],[6,7,8,9,10]])
tensor = np.array([
    [[255,255,3],[100,100,60],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]
])

In [6]:
vector_t = vector.T
print(vector_t)

[1 2 4 5 7]


In [7]:
matriz_t = matriz.T
print(matriz_t)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [8]:
tensor_t = tensor.T
print(tensor_t)

[[[255  10]
  [100  13]
  [  7  16]]

 [[255  11]
  [100  14]
  [  8  17]]

 [[  3  12]
  [ 60  15]
  [  9  18]]]


In [9]:
print(tensor_t.T)

[[[255 255   3]
  [100 100  60]
  [  7   8   9]]

 [[ 10  11  12]
  [ 13  14  15]
  [ 16  17  18]]]


In [12]:
print(tensor[0] + tensor[1])

[[265 266  15]
 [113 114  75]
 [ 23  25  27]]


In [13]:
print(tensor[0]*tensor[1])

[[2550 2805   36]
 [1300 1400  900]
 [ 112  136  162]]


In [14]:
tensor[0]

array([[255, 255,   3],
       [100, 100,  60],
       [  7,   8,   9]])

In [15]:
tensor[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])